apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-gateway.fullname" . }}-config
  labels: {{- include "llm-gateway.labels" . | nindent 4 }}
data:
  gateway.yaml: |
{{ .Files.Get "files/gateway.yaml" | indent 4 }}
